version: '3'
services:

  movie-finder:
    image: joulis1derful/movie-finder
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_URL=mongodb://mongodb:27017
      - DB_NAME=tmdb
      - API_KEY=52cc54558595d4caee5f1c68a7e7396f
      - SEARCH_MOVIES_URL=https://api.themoviedb.org/3/search/movie
      - TMDB_MOVIE_URL=https://api.themoviedb.org/3/movie
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis  

  mongodb:
    image: mongo:4.0.4
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example    
    volumes:
      - ./data/mongodb/db:/data/db  
    ports:
      - 27017:27017

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis